services:
  jekyll:
    platform: linux/amd64
    build: .
    ports:
      - 127.0.0.1:4000:4000
      - 127.0.0.1:35729:35729
    volumes:
      - $PWD:/srv/jekyll:Z
    command: jekyll serve --trace --watch --drafts --livereload # --incremental
